import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  line: {
    width: '100%',
    height: 5,
    backgroundColor: 'gray',
    position: 'absolute',
    marginVertical: 10,
  },
  info: {
    flex: 1,
    flexDirection: 'column', // 세로로 나열되도록 설정
    marginBottom: 60,
  },
  container: {
    flex: 1,
    backgroundColor: 'white',
    position: 'relative',
  },
  lineTop: {
    width: '100%',
    height: 2,
    backgroundColor: '#034198',
    position: 'absolute',
    top: 60,
  },
  lineMiddle: {
    width: '100%',
    height: 2,
    backgroundColor: '#034198',
    position: 'absolute',
    top: 450,
  },
  lineBottom: {
    width: '100%',
    height: 2,
    backgroundColor: '#034198',
    position: 'absolute',
    top: 583,
  },
  status: {
    width: 60,
    height: 17,
    textAlign: 'left',
    color: 'black',
    fontSize: 14,
    fontFamily: 'Roboto',
    fontWeight: '500',
    lineHeight: 20,
    letterSpacing: 0.10,
    position: 'absolute',
    left: 300,
    top: 525,
  },
  titleStatus: {
    width: 34,
    height: 17,
    textAlign: 'center',
    color: 'black',
    fontSize: 14,
    fontFamily: 'Roboto',
    fontWeight: '500',
    lineHeight: 20,
    letterSpacing: 0.10,
    position: 'absolute',
    left: 308,
    top: 498,
  },
  outTime: {
    width: 60,
    height: 17,
    textAlign: 'center',
    color: 'black',
    fontSize: 14,
    fontFamily: 'Roboto',
    fontWeight: '500',
    lineHeight: 20,
    letterSpacing: 0.10,
    position: 'absolute',
    left: 232,
    top: 525,
  },
  titleOutTime: {
    width: 58,
    height: 17,
    textAlign: 'center',
    color: 'black',
    fontSize: 14,
    fontFamily: 'Roboto',
    fontWeight: '500',
    lineHeight: 20,
    letterSpacing: 0.10,
    position: 'absolute',
    left: 235,
    top: 498,
  },
  inTime: {
    width: 58,
    height: 17,
    textAlign: 'center',
    color: 'black',
    fontSize: 14,
    fontFamily: 'Roboto',
    fontWeight: '500',
    lineHeight: 20,
    letterSpacing: 0.10,
    position: 'absolute',
    left: 168,
    top: 525,
  },
  titleInTime: {
    width: 58,
    height: 17,
    textAlign: 'center',
    color: 'black',
    fontSize: 14,
    fontFamily: 'Roboto',
    fontWeight: '500',
    lineHeight: 20,
    letterSpacing: 0.10,
    position: 'absolute',
    left: 168,
    top: 498,
  },
  name: {
    width: 45,
    height: 17,
    textAlign: 'center',
    color: 'black',
    fontSize: 14,
    fontFamily: 'Roboto',
    fontWeight: '500',
    lineHeight: 20,
    letterSpacing: 0.10,
    position: 'absolute',
    left: 116,
    top: 525,
  },
  titleName: {
    width: 33,
    height: 17,
    textAlign: 'center',
    color: 'black',
    fontSize: 14,
    fontFamily: 'Roboto',
    fontWeight: '500',
    lineHeight: 20,
    letterSpacing: 0.10,
    position: 'absolute',
    left: 120,
    top: 498,
  },
  circle: {
    width: 45,
    height: 45,
    backgroundColor: '#034198',
    borderRadius: 9999,
    position: 'absolute',
    left: 57,
    top: 498,
  },
  position: {
    width: 59,
    height: 34,
    textAlign: 'center',
    color: 'white',
    fontSize: 12,
    fontFamily: 'Inter',
    fontWeight: '400',
    lineHeight: 22,
    position: 'absolute',
    left: 51,
    top: 509,
  },
  iconContainer1: {
    width: 22,
    height: 22,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    right: 95,
    top: 21,
  },
  iconContainer2: {
    width: 22,
    height: 22,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    right: 55,
    top: 21,
  },
  iconContainer3: {
    width: 22,
    height: 22,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    right: 15,
    top: 21,
  },
  iconContainer4: {
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    left: 20,
    top: 508,
  },
  date: {
    width: 83,
    height: 17,
    textAlign: 'center',
    color: 'black',
    fontSize: 14,
    fontFamily: 'Roboto',
    fontWeight: 'bold',
    lineHeight: 20,
    letterSpacing: 0.10,
    position: 'absolute',
    left: 134,
    top: 459,
  },
  iconContainer5: {
    flexDirection: 'column',
    left: 15,
    position: 'absolute',
    marginTop: 10,
  },
  attendanceButton: {
    width: 66,
    height: 29,
    backgroundColor: '#034198',
    borderRadius: 5,
    position: 'absolute',
    left: 170,
    top: 599,
  },
  titleAttendance: {
    width: 33,
    height: 17,
    textAlign: 'center',
    color: 'white',
    fontSize: 14,
    fontFamily: 'Roboto',
    fontWeight: '500',
    lineHeight: 20,
    letterSpacing: 0.10,
    position: 'absolute',
    left: 17,
    top: 4,
  },
  calendar: {
    width: '100%',
    top: 93,
  },
  attendanceItemContainer: {
    marginBottom: 20,
    padding: 10,
    backgroundColor: '#f0f0f0',
    borderRadius: 5,
  },
});

export default styles;