import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
    position: 'relative',
  },
  iconContainer: {
    flexDirection: 'row',
    position: 'absolute',
    top: 19,
    right: 15,
  },
  icon: {
    width: 22,
    height: 22,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 10,
  },
  topLine: {
    width: '100%',
    height: 2,
    backgroundColor: '#034198',
    position: 'absolute',
    top: 52,
  },
  profilePictureContainer: {
    alignItems: 'center',
    position: 'absolute',
    top: 93,
    left: (width - 69) / 2,
  },
  profilePicture: {
    width: 69,
    height: 69,
    backgroundColor: '#034198',
    borderRadius: 9999,
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileRole: {
    color: 'white',
    fontSize: 20,
    fontFamily: 'Inter',
    fontWeight: '400',
  },
  name: {
    width: 180,
    height: 34,
    textAlign: 'center',
    color: 'black',
    fontSize: 22,
    fontFamily: 'Inter',
    fontWeight: '400',
    position: 'absolute',
    top: 165,
    left: (width - 180) / 2,
  },
  role: {
    width: 115,
    height: 22,
    textAlign: 'center',
    color: 'black',
    fontSize: 16,
    fontFamily: 'Inter',
    fontWeight: '400',
    position: 'absolute',
    top: 200,
    left: (width - 115) / 2,
  },
  separator: {
    width: '100%',
    height: 2,
    backgroundColor: '#034198',
    position: 'absolute',
    top: 276,
  },
  infoContainer: {
    position: 'absolute',
    top: 300,
    width: '100%',
    paddingHorizontal: 20,
  },
  infoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 5, 
  },
  infoLabel: {
    color: 'black',
    fontSize: 20,
    fontFamily: 'Inter',
    fontWeight: '400',
    flex: 1, 
    textAlign: 'left', 
    marginLeft: 5,
  },
  infoValue: {
    color: 'black',
    fontSize: 20,
    fontFamily: 'Inter',
    fontWeight: '400',
    textAlign: 'left', 
    flex: 1, 
  },
  logoutButton: {
    width: 75,
    height: 36,
    backgroundColor: '#034198',
    borderRadius: 5,
    position: 'absolute',
    top: 640,
    right: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  logoutText: {
    color: 'white',
    fontSize: 13,
    fontFamily: 'Inter',
    fontWeight: '400',
    lineHeight: 22,
  },
});

export default styles;
